### ISSUE TITLE
Drawer style should inherit from the applied theme

### ISSUE THREAD

**Issue by aboganas** [NativeScript/template-drawer-navigation#46]
First, thanks for this awesome template. I just have one issue with it. Instead of hardcoding the variables in _app-variables.scss, it should inherit the variables from the applied theme.

**Comment by lini** [comment]
Thank you for the suggestion. We have discussed this recently and came to the same conclusion - the template styles should be simplified. This will happen after the core theme is updated as well, because we want to borrow some of the template styles for the new core theme. Unfortunately I am not aware when the core theme update will happen.

**Comment by LorenDorez** [comment]
Do we have an idea when this will be done?

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/NativeScript#6048
