### ISSUE TITLE
Show drawer after login

### ISSUE THREAD

**Issue by handoyo** [NativeScript/template-drawer-navigation#72]
Hi, first of all sorry if i ask for help/guidance here instead of on StackOverflow nor Slack. I'm trying to navigate to a page that has the sidedrawer navigation after logged in but i failed. It doesn't go to the homepage. I'm adding a new login page within this template. Here's my login code:
```
function signIn() {
    user.login()
        .catch(function(error) {
            console.log(error);
            dialogsModule.alert({
            message: "Unfortunately we could not find your account.",
            okButtonText: "OK"
            });
            return Promise.reject();
            })
        .then(function() {
             frameModule.topmost().navigate("views/app-root/app-root");
    });
}
```

Thanks a lot.

**Comment by NickIliev** [comment]
@handoyo There[ is an open feature request](https://github.com/NativeScript/nativescript-angular/issues/1351) to support more possible scenarios with flexible navigation. The scenario you are trying to implement would require to create your drawer as root level and use as default page your **login** page. You could get a reference to your sidedrawer and explicitly disable the interaction when the login page is loaded (thus meaning that the user will never see a side drawer)

This logic is used in [this POC application](https://github.com/NickIliev/nativescript-ng-cosmos)  - the code base is Angular but the structure is pretty much the same (instead of `page-router-outlet` you should use `<Frame defaultPage="my-default-page">` in NativeScript Core). Here is the implementation logic explained step by step:

- the [root page contains sidedrawer](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/app/app.component.html#L2-L16) - change the Angular specific  `page-router-outlet` with 
```
<Frame id="myFrame" defaultPage="path-to-login-page">
```

- when the login page is loaded I am [explicitly disabling the sidedrawer via its reference](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/app/pages/login/login.component.ts#L39-L40). In NativeScript Core this can be done via `getFrameById` method.

e.g. JavaScript
```JavaScript
const getRootView = require("tns-core-modules/application").getRootView;

...

const drawer = getRootView();
drawer.gesturesEnabled = false;
```

And you can use the same approach to enable/close/open drawer via its reference in other pages.

**Comment by handoyo** [comment]
Thanks for the reply, please correct me if i'm wrong. The sample you gave me is how to hide the sidedrawer,right? May i know how to hide the login page and open other page after i have logged in? Thanks

**Comment by NickIliev** [comment]
@handoyo you can use Angular guards (e.g. `canActivate` & `canDeactivate`) - more details in [this documentation article](https://angular.io/guide/router#milestone-5-route-guards)
